spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: Postgresql@Om123

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  secretKey: huoiuwwwww82m87NRW0F8Ff90DhuirjffjzuioOU87rwaumiu9a8oauf4skv9EDa9gMECFgfadUafIjfisDA